stages:          # List of stages for jobs, and their order of execution
  - Test
  - Build and Release
  - Update Chart

##############################################################################
##                              Variables                                   ##
##############################################################################
variables:
  # AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/web-identity-token
  CD_CHART_REPO: process-engine-charts
  CD_GIT_REPOSITORY: git@gitlab.com:cs302-2023/g3-team8/project/k8s/process-engine-charts.git
  CD_MANIFEST_FILE: values.yaml
  APP_NAME: gitops-argocd-deploy
  CHART_FOLDER: helm

##############################################################################
##                Setup and Enable SSH                          ##
##############################################################################
.enable_ssh: &enable_ssh |-
  apk add --no-cache git
  mkdir -p /root/.ssh
  echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
  ssh-keyscan -H gitlab.com > /root/.ssh/known_hosts
  chmod 600 /root/.ssh/id_rsa

lint:
  stage: Test
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  script:
    # Use default .golangci.yml file from the image if one is not present in the project root.
    - '[ -e .golangci.yml ] || cp /golangci/.golangci.yml .'
    # Write the code coverage report to gl-code-quality-report.json
    # and print linting issues to stdout in the format: path/to/file:line description
    # remove `--issues-exit-code 0` or set to non-zero to fail the job if linting issues are detected
    - golangci-lint run --issues-exit-code 0 --print-issued-lines=false --out-format code-climate:gl-code-quality-report.json,line-number
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

unit-test:
  stage: Test
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker build -f docker/Dockerfile.test -t process-engine:test .
    - docker run --name process-engine-test-container process-engine:test go test -v ./... > test-results.txt
    - ls
    - docker cp process-engine-test-container:/app/test-results.txt .
  artifacts:
    when: always
    paths:
      - test-results.txt

release-image:
  stage: Build and Release
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --compress -t $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA -f ./docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA
      #when: manual


update_chart_manifest:
  stage: Update Chart
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  only:
    - main
  needs:
    - release-image
  variables:
    GIT_STRATEGY: none
  retry: 2
  before_script:
    - *enable_ssh
  script:
    # Configure Git
    - git config --global user.name $APP_NAME
    - git config --global user.email $APP_NAME"@gitlab.com"
    - git clone --single-branch --branch main $CD_GIT_REPOSITORY
    - cd $CD_CHART_REPO
    - cd $CHART_FOLDER
    # HELM Update
    - >
      tag=$(cat values.yaml | grep tag: | awk '{print $2}')
    - sed -i "s/$tag/$CI_COMMIT_SHORT_SHA/" values.yaml
    - cat $CD_MANIFEST_FILE
    - cd ..
    - git commit -am "🔥 update image tag" && git push origin main

