version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - "5672:5672"
      - "15672:15672"

  go-process-engine:
    container_name: process-engine
    image: process-engine:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    depends_on:
      - rabbitmq